#' Initialize a framework-package
#' 
#' @description This function is an alias for project_framework but with different default values. The configuration is adapted for projects that can be build as an R package.
#' @inheritParams project_framework
#' @seealso \code{\link{Rproj_init}}, \code{\link{git_init}}, 
#'   \code{\link{skeleton}}, \code{\link{project_framework}}
#' @author Frederik Sachser
#' @export
package_framework <- function(project_dir,
                          rstudio = TRUE,
                          init_git = TRUE,
                          init_packrat = FALSE,
                          custom_makeR = NULL,
                          target_makeR = 'make.R',
                          fun_dir = 'R',
                          source_files = c('prepare.R', 'visualize.Rmd'),
                          cache_dir = '.cache',
                          pkg_cran_install = c('utils', 'tools', 'rmarkdown', 'knitr', 'rstudioapi'),
                          pkg_cran_load = c('tidyverse'),
                          pkg_gh_install = NULL,
                          pkg_gh_load = NULL,
                          source_dir = 'files',
                          data_dir = 'inst/extdata',
                          target_dir_figure = 'figr',
                          target_dir_docs = 'docs',
                          target_dir_data = 'data',
                          listofdf = "GlobalEnv",
                          file_format = "RData",
                          delete_target_dir = TRUE,
                          devtools_create = TRUE,
                          rename_figure = TRUE,
                          rename_docs = TRUE,
                          log_filepath = 'meta/log.csv',
                          tree_target = 'meta/tree.txt',
                          include_hidden = FALSE,
                          filepath_git_summary = 'meta/git_summary.txt',
                          session_info_filepath = 'meta/session_info.txt',
                          spin_index = 999,
                          cache_index = 999,
                          knitr_cache = FALSE) {
  framework::project_framework(project_dir = project_dir,
                               rstudio = rstudio,
                               init_git = init_git,
                               init_packrat = init_packrat,
                               custom_makeR = custom_makeR,
                               target_makeR = target_makeR,
                               fun_dir = fun_dir,
                               source_files = source_files,
                               cache_dir = cache_dir,
                               pkg_cran_install = pkg_cran_install,
                               pkg_cran_load = pkg_cran_load,
                               pkg_gh_install = pkg_gh_install,
                               pkg_gh_load = pkg_gh_load,
                               source_dir = source_dir,
                               data_dir = data_dir,
                               target_dir_figure = target_dir_figure,
                               target_dir_docs = target_dir_docs,
                               target_dir_data = target_dir_data,
                               listofdf = listofdf,
                               file_format = file_format,
                               delete_target_dir = delete_target_dir,
                               devtools_create = devtools_create,
                               rename_figure = rename_figure,
                               rename_docs = rename_docs,
                               log_filepath = log_filepath,
                               tree_target = tree_target,
                               include_hidden = include_hidden,
                               filepath_git_summary = filepath_git_summary,
                               session_info_filepath = session_info_filepath,
                               spin_index = spin_index,
                               cache_index = cache_index,
                               knitr_cache = knitr_cache)
}

