#' Initialize a framework-package
#'
#' @description This function is an alias for project_framework but with different default values. The configuration is adapted for projects that can be build as R packages.
#' @inheritParams project_framework
#' @seealso \code{\link{skeleton}}, \code{\link{project_framework}}
#' @author Frederik Sachser
#' @export
package <- function(project_dir,
                              devtools_create = TRUE,
                              rstudio = TRUE,
                              init_git = TRUE,
                              init_packrat = FALSE,
                              input_files = c('prepare.R', 'visualize.Rmd'),
                              pkg_cran_install = c('utils', 'tools', 'rmarkdown', 'knitr', 'rstudioapi'),
                              pkg_cran_load = c('tidyverse'),
                              pkg_gh_install = NULL,
                              pkg_gh_load = NULL,
                              input_dir = 'files',
                              data_dir = 'inst/extdata',
                              cache_dir = '.cache',
                              fun_dir = 'R',
                              spin_index = 0,
                              cache_index = 999,
                              symlink_dir_input = NULL,
                              symlink_dir_docs = 'out/docs',
                              symlink_dir_figure = 'out',
                              rename_symlink_input = TRUE,
                              rename_symlink_docs = TRUE,
                              rename_symlink_figure = TRUE,
                              rebuild_figures = TRUE,
                              Rplots_device = 'grDevices::png',
                              target_dir_data = 'data',
                              listofdf = 'GlobalEnv',
                              data_extension = 'RData',
                              rebuild_target_dir_data = TRUE,
                              filepath_session_info = 'meta/session_info.txt',
                              filepath_log = 'meta/log.csv',
                              filepath_tree = 'meta/tree.txt',
                              filepath_warnings = 'meta/warnings.Rout',
                              tree_directory = 'getwd()',
                              include_hidden_tree = FALSE,
                              filepath_pkg_bib = 'meta/pkg.bib',
                              filepath_image = '.RData',
                              quiet_processing = TRUE,
                              summarize_session_info = FALSE,
                              summarize_df = FALSE,
                              summarize_memory = FALSE,
                              summarize_log = FALSE,
                              summarize_git = TRUE,
                              summarize_tree = FALSE,
                              summarize_warnings = FALSE) {
  framework::project_framework(project_dir = project_dir,
                               devtools_create = devtools_create,
                               rstudio = rstudio,
                               init_git = init_git,
                               init_packrat = init_packrat,
                               input_files = input_files,
                               pkg_cran_install = pkg_cran_install,
                               pkg_cran_load = pkg_cran_load,
                               pkg_gh_install = pkg_gh_install,
                               pkg_gh_load = pkg_gh_load,
                               input_dir = input_dir,
                               data_dir = data_dir,
                               cache_dir = cache_dir,
                               fun_dir = fun_dir,
                               spin_index = spin_index,
                               cache_index = cache_index,
                               symlink_dir_input = symlink_dir_input,
                               symlink_dir_docs = symlink_dir_docs,
                               symlink_dir_figure = symlink_dir_figure,
                               rename_symlink_input = rename_symlink_input,
                               rename_symlink_docs = rename_symlink_docs,
                               rename_symlink_figure = rename_symlink_figure,
                               rebuild_figures = rebuild_figures,
                               Rplots_device = Rplots_device,
                               target_dir_data = target_dir_data,
                               listofdf = listofdf,
                               data_extension = data_extension,
                               rebuild_target_dir_data = rebuild_target_dir_data,
                               filepath_session_info = filepath_session_info,
                               filepath_log = filepath_log,
                               filepath_tree = filepath_tree,
                               filepath_warnings = filepath_warnings,
                               tree_directory = tree_directory,
                               include_hidden_tree = include_hidden_tree,
                               filepath_pkg_bib = filepath_pkg_bib,
                               filepath_image = filepath_image,
                               quiet_processing = quiet_processing,
                               summarize_session_info = summarize_session_info,
                               summarize_df = summarize_df,
                               summarize_memory = summarize_memory,
                               summarize_log = summarize_log,
                               summarize_git = summarize_git,
                               summarize_tree = summarize_tree,
                               summarize_warnings = summarize_warnings)
}

